package com.app.entities;

public enum Category {
	GROCERY_STAPLES,
	DAILY_ESSENTIALS,
	DAIRY_FROZEN,
	DMART_BRANDS,
	HOME_PERSONAL_CARE,
	BED_BATH,
	HOME_APPLIANCES,
	CROCKERY,
	ELECTRONICS,
	FOOTWEAR,
	LUGGAGE,
	TOYS_GAMES,
	PLASTIC_CONTAINERS,
	KID_APPAREL,
	WOMEN_APPAREL,
	MEN_APPAREL,
	FRUITS_VEGETABLES
}
